/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clubmanager.gui.view;

/**
 *
 * @author johannes
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateView1 = new clubmanager.gui.view.UpdateView();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        registryView1 = new clubmanager.gui.view.RegistryView();
        searchView2 = new clubmanager.gui.view.SearchView();
        searchView1 = new clubmanager.gui.view.SearchView();
        updateView2 = new clubmanager.gui.view.UpdateView();

        javax.swing.GroupLayout updateView1Layout = new javax.swing.GroupLayout(updateView1);
        updateView1.setLayout(updateView1Layout);
        updateView1Layout.setHorizontalGroup(
            updateView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        updateView1Layout.setVerticalGroup(
            updateView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 480));

        registryView1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registryView1FocusGained(evt);
            }
        });
        jTabbedPane1.addTab("Registry", registryView1);
        jTabbedPane1.addTab("Search", searchView2);

        javax.swing.GroupLayout searchView1Layout = new javax.swing.GroupLayout(searchView1);
        searchView1.setLayout(searchView1Layout);
        searchView1Layout.setHorizontalGroup(
            searchView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateView2, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );
        searchView1Layout.setVerticalGroup(
            searchView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateView2, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Update", searchView1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registryView1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registryView1FocusGained
                // TODO add your handling code here:
    }//GEN-LAST:event_registryView1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void StartGUI() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private clubmanager.gui.view.RegistryView registryView1;
    private clubmanager.gui.view.SearchView searchView1;
    private clubmanager.gui.view.SearchView searchView2;
    private clubmanager.gui.view.UpdateView updateView1;
    private clubmanager.gui.view.UpdateView updateView2;
    // End of variables declaration//GEN-END:variables
}
